name: Deploy to Beget
on:
  push:
    branches: [ "master" ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: List files in repository
        # Эта команда покажет ВСЕ файлы, которые видит GitHub. 
        # Мы точно узнаем правильный путь к .csproj
        run: find . -maxdepth 3 -not -path '*/.*'

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

      - name: Publish project
        run: |
          # Мы используем wildcard (звездочку), чтобы .NET сам нашел проект в папке
          dotnet publish WebApplication2/*.csproj -c Release -o ./publish_output
          echo "Проверка содержимого после публикации:"
          ls -la ./publish_output

      - name: Deploy to Server via SSH
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SSH_KEY }}
          source: "publish_output/*"
          target: "/var/www/my-app"
          strip_components: 1