name: Deploy to Beget

on:
  push:
    branches: [ "master" ] # Проверьте, что в GitHub ветка именно master!

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      # 1. Диагностика (поможет нам увидеть структуру папок)
      - name: Show structure
        run: ls -R

      # 2. Настройка .NET
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

      # 3. Публикация (создаем папку publish_output)
      - name: Publish project
        run: dotnet publish WebApplication2/WebApplication2.csproj -c Release -o ./publish_output

      # 4. Проверка, что файлы создались (для логов)
      - name: Check publish folder
        run: ls -la ./publish_output

      # 5. Копирование на сервер
      - name: Deploy via SCP
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SSH_KEY }}
          source: "publish_output/*"
          target: "/var/www/my-app"
          strip_components: 1

      # 6. Перезапуск службы на сервере
      - name: Restart Service
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SSH_KEY }}
          script: sudo systemctl restart myapp.service